- main.tf
Removed the tags from the ECS cluster ([again](https://github.com/schubergphilis/terraform-aws-mcaf-fargate/commit/540eddbf8f86519ce4c7ce872d96af9150ad9817)).
Tagging is only possible with the "new ARN format". Which is currently a manual opt-in, and new ECS clusters will get the new format from 1-2-2020 ([source](https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-ecs-and-aws-fargate-now-allow-resources-tagging-/
)).
To prevent people adding the tags again in the future (with good intentions) kept the code but commented, with documentation on why it's disabled.
> Remove tags from the ECS cluster (not supported)

- alb.tf
- dns.tf
- main.tf
- outputs.tf
- variables.tf
This PR adds the DNS configuration (route53) to the MCAF module. This simplifies the usage of the module and allows to improve the HTTP->HTTPS functionality.
The redirect now redirects explicitly to the given domain (`subdomain`) instead of the user input. This prevents possible spoofing the redirect by specifying a different Host in the request
>  [IOT-478] Add DNS configuration and improve redirect

- lb.tf
- variables.tf
This will add in target group health check settings as variables which will make it possble to pass custom values when using the module. The variables have defaults which makes them optional and are set to the original hardcoded values.
> Add target group health check settings

- README.md
- lb.tf
```
Error: error creating network Load Balancer: ValidationError: You can specify either subnets or subnet mappings, not both
```
Missed this, currently breaks when using the Elastic IP's
> Fix subnet specification

- README.md
- lb.tf
- outputs.tf
- variables.tf
This PR adds the "Cross zone loadbalancing" ([documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html)) feature to the Network loadbalancers
> Add cross-zone LB feature

- dns.tf
- lb.tf
- outputs.tf
This PR fixes some TF issues that popped up when building new infrastructure from scratch.
```
on .terraform/modules/br001oc_cb_opco.opco_proxy.proxy_container/dns.tf line 36, in resource "aws_route53_record" "cert_validation":
36:   for_each = {
37:     for dvo in aws_acm_certificate.default[0].domain_validation_options : dvo.domain_name => {
38:       name   = dvo.resource_record_name
39:       record = dvo.resource_record_value
40:       type   = dvo.resource_record_type
41:     }
42:   }
```
Same fix implemented as in https://github.com/schubergphilis/terraform-aws-mcaf-cloudfront/pull/50
```
Error: Invalid for_each argument
on .terraform/modules/br001oc_cb_opco.opco_proxy.proxy_container/lb.tf line 44, in resource "aws_eip" "lb":
44:   for_each = toset(local.eip_subnets)
The …
```
> Rebuild to fix TF issues

- dns.tf
- lb.tf
- variables.tf
If the protocol is `TCP`, only a TCP listener is created. And that one is not (and cannot) be asigned to a certificate.
But there is certificate created which is not in use. 
As a result there is a danling certificate which is not eligable for renewal, ending up in Security Hub (`ACM certificates should be renewed after a specified time period` ([source](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-acm-1)).
This PR fixes:
- Don't create a certificate for TCP
- Add validation on protocal variable (`HTTP` or `TCP`)
- Remove single reference to `HTTPS` as protocol value. HTTP = HTTPS basically
> Don't create certificate if protocol is TCP

- dns.tf
Made a small mistake with the TCP listener certificate check:
```
on xxx/dns.tf line 6, in locals:
│    6:   certificate_arn   = var.certificate_arn != null ? var.certificate_arn : aws_acm_certificate.default[0].arn
│     ├────────────────
│     │ aws_acm_certificate.default is empty tuple
│ 
│ The given key does not identify an element in this collection value.
╵
```
> Fix certificate arn determination

- main.tf
This PR makes sure the tags are being applied to the Fargate task that is started. It cannot be set explicitly, but the `propagate_tags` attribute tell which tags to be propagated [source](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#ECS-CreateService-request-propagateTags). Currently the tasks are not tagged making cost insights annoying/impossible.
The value is "hardcoded" to `TASK_DEFINITION` for the reason that we cannot set the tags on the ECS Service (https://github.com/hashicorp/terraform-provider-aws/issues/7373)
> Add tag propagation to the Fargate Task

- README.md
- main.tf
- variables.tf
This PR adds (and by default) enabled CloudWatch Container Insights ([source](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html))
Popped up as a TFSec warning:
```
Legacy ID:  AWS090
Impact:     Not all metrics and logs may be gathered for containers when Container Insights isn't enabled
Resolution: Enable Container Insights
More Info:
- https://tfsec.dev/docs/aws/ecs/enable-container-insight#aws/ecs 
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster#setting 
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html 
```
> Add (and by default enabled) ContainerInsights

- .github/workflows/terraform.yml
- README.md
- lb.tf
- main.tf
- variables.tf
- versions.tf
This PR updates the module to work with Terraform AWS provider V4:
- Refactored `capacity_providers` of the `aws_ecs_cluster` to the `aws_ecs_cluster_capacity_providers` resource.
- Bumped used module.
> Support AWS provider V4

- README.md
- dns.tf
- main.tf
- variables.tf
The local now returns ‘{}’ instead of ‘null’ resulting in a count-error in lb.tf (in load_balancer_count count)
> Fixed local to return null if var.load_balancer_subnet_ids is not set

- README.md
- lb.tf
- versions.tf
This PR resolved the `aws_eip` deprecation warning that's introduced in [provider v5](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#500-may-25-2023)
See also https://github.com/schubergphilis/terraform-aws-mcaf-vpc/pull/54
> Resolve eip deprecation warning

- efs.tf
- main.tf
- variables.tf
**Attaching an EFS file system to an ECS Task**
When enable_efs variable set to true, and EFS volume is created and attached to the container.
EFS configuration uses transit_encryption enabled to comply with tfsec: https://aquasecurity.github.io/tfsec/v1.8.0/checks/aws/ecs/enable-in-transit-encryption/
optional mount_points variable can be used to indicate container paths:
"mountPoints": [
{
"containerPath": "/usr/share/nginx/html"
}
]
> Attaching an EFS file system to an ECS Task

- efs.tf
Problem: 
When enable_efs feature flag is enabled, the resources created but the volume is not attached at runtime.
Story:
While the previous development creates resources properly, the EFS volume was not being mounted when the container is being commissioned. Note that this is not about TF but a runtime issue. I thought container is in a subnet but there is no way to communicate to EFS service. This PR adds aws_security_group meanwhile adds data encryption at rest.
Testing: 
Terraform validated, applied and seen the resources created. I experimented the volume creation at AWS console manually. I also tried to deploy all workload environment in a sandbox account to see all process end to end, however this has failed for many reasons. I can't be sure 100% but this should work.
Heads Up: …
> add aws_security_group and enable data encryption in rest

- efs.tf
- main.tf
Problem: mountPoints setting in aws_ecs_task_definition is not effective.
Solution: Same efs name must be passed to aws_efs_file_system as a Name variable in tags collection.
References:
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#tags
- https://docs.aws.amazon.com/efs/latest/ug/API_CreateFileSystem.html
Example sections for expected result:
```
updated_mount_points = [
{
"containerPath" = "/data"
"sourceVolume" = "efs-name" # must be same in aws_efs_file_system.default.tags.Name
},
]
```
```
resource "aws_efs_file_system" "default" {
...
creation_token = "efs-name"
tags = {
Name = "efs-name"
}
}
```
> Add EFS name

- templates/container_definition.tpl
Add a missing entry to the template file which defines ecs_task_definition.
mountPoints comes from variables, processed in locals and given as parameter to ecs task definition template.
For testing, I tried to see the result in tf plan, it doesn't give an error but it doesn't show that detail either.
> add mountPoints to the template

- dns.tf
This PR changes the Route53 record from a CNAME to an Alias.
Trusted advisor actually hinted on this, also implemented this in the [Cloudfront module already](https://github.com/schubergphilis/terraform-aws-mcaf-cloudfront/pull/117)
> Change the DNS record to an ALIAS

- main.tf
- variables.tf
**Problem:**
Containers with long startup times are failing to commission successfully due to load balancer health checks terminating them before the application has time to start up and become ready.
**Solution:**
Introduce the `health_check_grace_period_seconds` parameter to the ECS service resource. This parameter allows us to specify a grace period during which ECS will ignore failing load balancer health checks on newly instantiated tasks, preventing premature shutdown.
**Details:**
- Added `health_check_grace_period_seconds` parameter to the `aws_ecs_service` resource.
- Created a new variable `health_check_grace_period_seconds` with a default value of null to maintain backwards compatibility.
While the module already has a …
> Add health check grace period to ECS service

- README.md
- dns.tf
- efs.tf
- examples/basic/main.tf
- lb.tf
- main.tf
- terraform.tf
- variables.tf
⚠️ **This introduces a breaking change as it requires at least v6 of the AWS provider.** ⚠️
This pull request updates the MCAF Fargate Terraform module to support explicit region configuration and upgrades the AWS provider version. The main focus is on allowing users to specify the AWS region for all related resources, which improves multi-region compatibility and control. Additionally, the AWS provider version is updated to the latest major version.
**Region configuration improvements:** 
* Added a new `region` variable in `variables.tf` to allow users to specify the AWS region for the vpc and related resources. If omitted, the default provider region is used.
* Updated all resources to accept and use the `region` variable. This ensures consistent resource creation in the specified …
> feat!: Add region support
